### ISSUE TITLE
Frame refuses to display

### ISSUE THREAD

**Issue by Omar-Ali** [Yoctol/react-messenger-customer-chat#27]
I'm trying to embed the component but the frame refuses to load and I'm facing this console error:

<img width="1429" alt="screen shot 2018-07-22 at 1 08 35 pm" src="https://user-images.githubusercontent.com/10078621/43045020-f586caa4-8db0-11e8-8a5d-463ae27d8031.png">

**Comment by chentsulin** [comment]
From: https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin#debug-tips

```
If you see a console error like "Refused to display *** in a frame because an ancestor violates the following Content Security Policy directive: ***", check that the domain of the page the plugin is being rendered on has been whitelisted. Also make sure you didn't set the Referrer-Policy header to no-referrer.
```

**Comment by Omar-Ali** [comment]
I'm still testing it on my localhost, I've already set the referrer policy to 'no-referrer' but I don't know how to whitelist my domain, nor my localhost.

**Comment by tw0517tw** [comment]
Maybe you can try to report on [Facebook bug report](https://developers.facebook.com/bugs/) or ask in [Messenger Platform dev group](https://www.facebook.com/groups/messengerplatform/)

**Comment by Omar-Ali** [comment]
The problem just fixed a month later, I think it was something from Facebook end.

**Comment by sonic1981** [comment]
The issue here is that Facebook SDK has a white list, you can't white list localhost. You can work around it by using your [hosts file](https://docs.rackspace.com/support/how-to/modify-your-hosts-file/) to render localhost on your domain name, add a record into your hosts file something like:

```
127.0.0.1 www.mydomain.com
```

Then go to www.mydomain.com where this domain is white listed in facebook and it should work.
