### ISSUE TITLE
The button isn't coming up in Firefox or any other platforms

### ISSUE THREAD

**Issue by bho01** [Yoctol/react-messenger-customer-chat#42]
I followed the instructions and I am using localhost so there isn't anyway for me to whitelist. However, the button does not render.

**Comment by paramshah10** [comment]
Did you find a workaround?

**Comment by bho01** [comment]
> Did you find a workaround?

not yet

**Comment by chentsulin** [comment]
Hi @bho01 @paramshah10 
You can't use localhost to access the plugin. You must correctly list the whitelisted domains, so that facebook can know this fan page allows users to send messages on the certain webpages. Or, this would be a security issue.

See https://github.com/Yoctol/react-messenger-customer-chat/issues/41#issuecomment-650793224

**Comment by chentsulin** [comment]
> For security reasons, the plugin will only render when loaded on a domain that you have whitelisted.

For more information, please checkout https://developers.facebook.com/docs/messenger-platform/discovery/facebook-chat-plugin?locale=en_US
